99 auth phone number
devsummit/app pull request #110
Opened 2017-08-22 12:14 UTC by caudaganesh

#99 

### Breakdown:
- [x] Add account kit for login and register with mobile phone
- [x] Modify redux to match account kit
- [x] Modify some components and styling to match account kit

2017-08-22 14:45 UTC, andy-shi88 commented
@caudaganesh there are conflicts, please fix them first.

2017-08-23 05:17 UTC, caudaganesh commented
okay will do it tonight sir

On Wed, Aug 23, 2017 at 12:15 PM, Ganesh Cauda <caudaganesh@gmail.com>
wrote:

>
> On Tue, Aug 22, 2017 at 9:45 PM, Andy Shi <notifications@github.com>
> wrote:
>
>> @caudaganesh <https://github.com/caudaganesh> there are conflicts,
>> please fix them first.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/devsummit/app/pull/110#issuecomment-324049069>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AcUcXyPSbJJSo0pmat1BJJT6GDwy6uakks5saul5gaJpZM4O-h8u>
>> .
>>
>
>

2017-08-24 03:29 UTC, andy-shi88 requested changes
@caudaganesh  have a look

2017-08-24 03:29 UTC, andy-shi88 commented on app/containers/RegisterPhone/actions.js
> +const ROLES = {
please move it to `constants.js`

2017-08-24 03:29 UTC, andy-shi88 commented on app/containers/RegisterPhone/actions.js
> +        Alert.alert('Registration failed (T_T)');
should return some condition to `view` that trigger this alert in the `index` and remove the emoticon btw 😆 @caudaganesh

2017-08-24 03:29 UTC, andy-shi88 commented on app/containers/RegisterPhone/index.js
> +    console.log(this.props)
clean the log

2017-08-24 03:29 UTC, andy-shi88 commented on app/containers/RegisterPhone/index.js
> +      console.warn('User canceled login')
clean the log

2017-08-24 03:29 UTC, andy-shi88 commented on app/containers/RegisterPhone/index.js
> +      console.log('isregistering...');
again the log.

2017-08-24 04:40 UTC, andy-shi88 approved these changes

2017-08-24 04:40 UTC, merged